accounts/urls.py
from django.urls import path
from accounts import views


app_name = 'auth'

# Define urls
urlpatterns = [
    path('login', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_registration, name='register'),

    # Password reset URLs
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

tapp/urls.py
from django.urls import path
from .views import TaskList, TaskDetail, TaskCreate, TaskUpdate, TaskDeleteView, TaskListApiView, TaskListByApi

# Route
urlpatterns = [
    path('', TaskList.as_view(), name='list'),
    path('add/', TaskCreate.as_view(), name='add'),
    path('detail/<int:pk>/', TaskDetail.as_view(), name='detail'),
    path('update/<int:pk>/', TaskUpdate.as_view(), name='update'),
    path('delete/<int:pk>', TaskDeleteView.as_view(), name='delete'),

    path('api/tasks/', TaskListApiView.as_view(), name='api'),
    path('api-list/', TaskListByApi.as_view(), name='api-list'),
]

tms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tapp.urls')),
    path('auth/', include('accounts.urls', namespace='auth')),
    path('accounts/', include('allauth.urls')),
]

# TODO: Configure media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += debug_toolbar_urls()

accounts/models.py
from django.db import models

# Create your models here.

tapp/models.py
from django.db import models
from django.db.models.signals import post_save, pre_save

# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return f"{self.name}" 


class Tag(models.Model):
    name = models.CharField(max_length=26)

    def __str__(self):
        return f"{self.name}" 
    
    
class Task(models.Model):
    status_choices = {
        'due': 'Pending',
        'done': 'Completed'
    }
    
    title = models.CharField(max_length=60)
    description = models.CharField(max_length=255)
    status = models.CharField(max_length=10, choices=status_choices, default='due')
    created_at = models.DateField(auto_now=True)
    due_date = models.DateField()
    avator = models.ImageField(upload_to='profiles/', blank=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag, related_name='tasks')


    def __str__(self):
        return f"{self.title} {self.description} {self.status}"
    

    def get_tag_name(self):
        return 'Accessed'


# SENDER & RECEIVER
def save_task(sender, instance, **kwargs):
    print("Signal received")

post_save.connect(save_task, sender=Task)
pre_save.connect(save_task, sender=Author)

tapp/forms.py
from django import forms
from .models import Task

# Defining our forms
class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'status', 'due_date', 'author', 'tag']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy

# Create your views here.
def user_registration(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('list')
    
    else:
        form = UserCreationForm()

    context = {
        'form': form,
        'title': 'Register'
    }
    return render(request, 'register.html', context)


def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('list')
    else:
        form = AuthenticationForm()

    context = {
        'form': form,
        'title': 'Login'
    }

    return render(request, 'login.html', context)


def user_logout(request):
    logout(request)
    return redirect('auth:login')


class CustomPasswordResetView(PasswordResetView):
    template_name = 'registration/password_reset_form.html'
    success_url = reverse_lazy('auth:password_reset_done')
    email_template_name = 'registration/password_reset_email.html'

class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'registration/password_reset_done.html'

class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = "registration/password_reset_confirm.html"
    success_url = reverse_lazy("password_reset_complete")

class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = "registration/password_reset_complete.html"

tapp/views.py
from typing import Any
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Task
from .forms import TaskForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator

# Asynchronous Programming Imports
import asyncio
from asgiref.sync import sync_to_async
from django.views import View
from django.http import JsonResponse

# Logic
class TaskList(ListView):
    model = Task

    def get(self, request):
        tasks = Task.objects.all().order_by('due_date')
        paginator = Paginator(tasks, 4, 1, allow_empty_first_page=True)
        page = request.GET.get('page')

        try:
            paginated_tasks = paginator.page(page)
        except PageNotAnInteger:
            paginated_tasks = paginator.page(1)
        except EmptyPage:
            paginated_tasks = paginator.page(paginator.num_pages)


        context = {
            'tasks': paginated_tasks,
            'title': 'Task List'
        }

        return render(request, 'tapp/index.html', context)


class TaskListByApi(ListView):
    model = Task
    template_name = 'tapp/api.html'

class TaskListApiView(View):
    async def get(self, request):
        await asyncio.sleep(5)
        tasks = await sync_to_async(lambda: list(Task.objects.values().order_by('due_date')))()
        return JsonResponse(tasks, safe=False)

class TaskDetail(DetailView):
    model = Task
    template_name = 'tapp/detail.html'
    context_object_name = 'task'

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['title'] = 'Task Detail'
        context['tags'] = Task.get_tag_name(self)
        return context


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    form = TaskForm
    fields = ['title', 'description', 'status', 'due_date', 'author', 'tag']
    success_url = '/'
    template_name = 'tapp/create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Task Create'
        return context


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    form = TaskForm
    fields = ['title', 'description', 'status', 'due_date', 'avator', 'author', 'tag']
    success_url = '/'
    template_name = 'tapp/create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Task Update'
        return context

@method_decorator(login_required, name='dispatch')
class TaskDeleteView(DeleteView):
    model = Task
    template_name = 'tapp/delete.html'
    context_object_name = 'task'
    success_url = '/'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['title'] = 'Task Delete'
        return context

accounts/templates/login.html
{% extends 'base.html' %} {% block content %} {% load socialaccount %}

<h1>User Login</h1>
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Login</button>

  <a
    href="{% provider_login_url 'google' %}"
    next="/"
    class="btn btn-outline-primary text-white"
    >Google</a
  >
</form>

<!-- Child temp -->
{% endblock content %}

accounts/templates/register.html
{% extends 'base.html' %} 

{% block content %}

<h1>User Registration</h1>
<form method="post">
{% csrf_token %} {{ form.as_p }}
<button type="submit">Register</button>
</form>

{% endblock content %}

tapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TodoApp {% if title %}| {{ title }}{% endif %}</title>

    <!-- Bootstrap -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css"
    />

    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
    />

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <main>
      <header>
        {% include 'nav.html' %}
      </header>
      <section class="vh-100 gradient-custom-2">
        <div class="container py-5 h-100">
          <div
            class="row d-flex justify-content-center align-items-center h-100"
          >
            <div class="col-md-12 col-xl-10">
              <div class="card mask-custom">
                <div class="card-body p-4 text-white">
                  <div class="text-center pt-3 pb-2">
                    <img
                      src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-todo-list/check1.webp"
                      alt="Check"
                      width="60"
                    />
                    <h2 class="my-4">
                      {% if title %}{{ title }}{% else %} TodoApp {% endif %}
                    </h2>
                  </div>

                  {% block content %}

                  <!-- Child templates -->

                  {% endblock content %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.min.js"></script>
  </body>
</html>

tapp/templates/nav.html
<nav class="navbar navbar-dark bg-light text-white">
  <ul class="nav">
    <li><a href="{% url 'list' %}" class="nav nav-item">Home</a></li>
    {% if user.is_authenticated %}
    <li>
      <a href="{% url 'auth:logout' %}" class="nav nav-item btn btn-danger"
        >Logout {{ user.username }}</a
      >
    </li>
    {% else %}
    <li>
      <a href="{% url 'auth:login' %}" class="nav nav-item btn btn-primary"
        >Login</a
      >
    </li>
    {% endif %}
  </ul>
</nav>

tapp/templates/tapp/api.html
{% extends 'base.html' %} {% block content %}
<section>
  <h1>Api Tasks</h1>
  <ul id="task_list"></ul>
  <script>
    async function fetchTasks() {
      const response = await fetch("/api/tasks/");
      const tasks = await response.json();
      const task_list = document.getElementById("task_list");
      task_list.innerHTML = "";
      tasks.forEach((task) => {
        const li = document.createElement("li");
        li.textContent = `${task.title} - ${task.description}`;
        task_list.appendChild(li);
      });
    }
    fetchTasks();
  </script>
</section>
{% endblock content %}

tapp/templates/tapp/create.html
{% extends 'base.html' %} {% block content %}

<div class="bg-white text-dark p-3">
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit" class="btn btn-outline-info mx-3">Add Task</button>
  </form>
</div>

{% endblock content %}

tapp/templates/tapp/delete.html
{% extends 'base.html' %} {% block content %}

<div class="bg-white text-dark">
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{ task.title }} ?</p>
    <button type="submit" class="btn btn-outline-danger">
      Yes, Delete Task
    </button>
    <a href="{% url 'list' %}" class="btn btn-outline-warning">Cancel</a>
  </form>
</div>

{% endblock content %}

tapp/templates/tapp/detail.html
{% extends 'base.html' %} {% block content %}

<div class="bg-white container text-dark">
  <div>
    <p>Title: {{ task.title }}</p>
    <p>Description: {{ task.description}}</p>
    <p>Status: {{ task.status }}</p>
    <p>Date: {{ task.due_date }}</p>
    <ol>
      Tags: {{ tags }}
    </ol>
  </div>

  <div>
    <a href="{% url 'update' task.id %}" class="btn btn-primary">Update Task</a>
    <a href="{% url 'delete' task.id %}" class="btn btn-primary">Delete Task</a>
  </div>
</div>
{% endblock content %}

tapp/templates/tapp/index.html
{% extends 'base.html' %} {% block content %}

<table class="table text-white mb-0 bg-dark">
  <thead>
    <tr>
      <th scope="col">Author</th>
      <th scope="col">Task</th>
      <th scope="col">Due date</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for task in tasks %}
    <tr class="fw-normal">
      <th>
        <img
          src="{{ task.avator.url }}"
          alt="avatar 1"
          style="width: 45px; height: auto"
        />
        <span class="ms-2">{{ task.author.name|capfirst }}</span>
      </th>
      <td class="align-middle">
        <span><a href="{% url 'detail' task.id %}">{{ task.title }}</a></span>
      </td>
      <td class="align-middle">
        <h6 class="mb-0">
          <span class="badge bg-danger">{{ task.due_date }}</span>
        </h6>
      </td>
      <td class="align-middle">
        <a href="{% url 'update' task.id %}" data-mdb-tooltip-init title="Done"
          ><i class="fas fa-edit fa-lg text-success me-3"></i
        ></a>
        <a
          href="{% url 'delete' task.id %}"
          data-mdb-tooltip-init
          title="Remove"
          ><i class="fas fa-trash-alt fa-lg text-warning"></i
        ></a>
      </td>
    </tr>
    {% endfor %}

    <a href="{% url 'add' %}" class="btn btn-primary"
      ><i class="fas fa-add"></i> Add new Task</a
    >
  </tbody>
</table>

<div class="pagination">
  <!-- PREVIOUS Page -->
  {% if tasks.has_previous %}

  <a href="?page=1">First</a>
  <a href="?page={{ tasks.previous_page_number }}">previous</a>

  {% endif %}

  <!-- CURRENT Page -->
  <span> Page {{ tasks.number }} of {{ tasks.paginator.num_pages }} </span>

  <!-- NEXT Page -->
  {% if tasks.has_next %}

  <a href="?page={{ tasks.next_page_number }}">next</a>
  <a href="?page={{ tasks.paginator.num_pages }}">Last</a>

  {% endif %}
</div>

{% endblock content %}

tapp/templates/tapp/update.html
{% extends 'base.html' %} {% block content %}

<div class="bg-white container">
  <form method="post" enctype="multipart/form-data" class="form-control">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Update</button>
  </form>
</div>

{% endblock content %}